### ISSUE TITLE
Hide "Submit Changes" button until something has been changed

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#58]

**Comment by DaviTeodoro** [comment]
@davidheyman Is there a way to know, from the backend, if there are pending features to commit?  It would be more reliable, because it is a state that should be held even though the user finish his session. 
For instance if the user draws a feature and accidentally closes the browser the submit button should visible when he come back.

**Comment by davidheyman** [comment]
I've added a route at `GET /api/v1/edits` that will give you the number of open edits for the user making the request that aren't part of a change set.

**Comment by DaviTeodoro** [comment]
thank you https://github.com/axismaps/levant-carta-next/commit/a2d346c185dbb0289b00cc389c16d581ba91a691
